Repository microsoft/mu_devops, pull requests merged in 2022-12, with the labels that each got.

#43 ReadMe.rst: Add file sync status badge
  ReadMe.rst
Labels: type:documentation, impact:non-functional

#48 label-issues: Invert functional impact label logic
  .sync/workflows/config/label-issues/regex-pull-requests.yml
Labels: type:bug

#15 InstallMarkdownLint.yml: Update to markdownlint-cli 0.31.1
  Steps/InstallMarkdownLint.yml
Labels: semver:patch

#56 .sync/azure-pipelines: Swap CLANGPDB VM image name
  .sync/azure_pipelines/matrix_dependent/Ubuntu-CLANGPDB.yml
  .sync/azure_pipelines/matrix_dependent/Windows-CLANGPDB.yml
Labels: type:bug

#61 Fix incorrect changes to mu_feature_config custom Ubuntu-GCC5 pipeline
  .sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml
Labels: type:bug

#55 Add Issue Triage workflow
  .github/Labels.yml
  .github/workflows/IssueTriager.yml
  .sync/Files.yml
  .sync/workflows/config/triage-issues/advanced-issue-labeler.yml
  .sync/workflows/leaf/triage-issues.yml
  ReadMe.rst
Labels: type:enhancement

#60 Add reusable Auto Merge workflow
  .github/workflows/AutoMerger.yml
  .sync/Files.yml
  .sync/workflows/leaf/auto-merge.yml
  ReadMe.rst
Labels: type:enhancement

#66 .sync: Set recent workflows to a fixed version of mu_devops
  .sync/Files.yml
  .sync/workflows/leaf/auto-merge.yml
  .sync/workflows/leaf/release-draft.yml
  .sync/workflows/leaf/triage-issues.yml
Labels: semver:patch

#67 .sync/workflows: Add file sync notice to some files
  .sync/workflows/config/label-issues/file-paths.yml
  .sync/workflows/config/label-issues/regex-pull-requests.yml
  .sync/workflows/config/triage-issues/advanced-issue-labeler.yml
Labels: impact:non-functional, semver:patch

#70 Add pull-request best practices guide
  .sync/github_templates/contributing/CONTRIBUTING.md
  .sync/github_templates/pull_requests/pull_request_template.md
Labels: type:documentation, impact:non-functional
