Repository microsoft/mu_devops, pull requests merged in 2023-09, with the labels that each got.

#239 Add CodeQL platform GitHub workflow
  .sync/Files.yml
  .sync/workflows/leaf/codeql-platform.yml
Labels: type:enhancement, type:feature-request

#240 .sync/workflows/leaf/codeql-platform.yml: Bump actions/checkout to v4
  .sync/workflows/leaf/codeql-platform.yml
Labels: semver:patch

#241 .sync/rust_config/Makefile.toml: Add check task
  .sync/rust_config/Makefile.toml
Labels: type:enhancement

#242 .sync/workflows/leaf/codeql: Remove build dirs
  .sync/workflows/leaf/codeql-platform.yml
  .sync/workflows/leaf/codeql.yml
Labels: type:enhancement

#247 RustSetupSteps: Add target triple detection
  .sync/azure_pipelines/RustSetupSteps.yml
  Steps/RustSetupSteps.yml
Labels: semver:patch

#249 .sync/Makefile.toml: Resolve cargo-tarpaulin breaking changes
  .sync/rust_config/Makefile.toml
Labels: type:bug, impact:non-functional

#246 Conditionalize RustSetupSteps.yml to Non-Self-Hosted Agents
  .sync/azure_pipelines/MuDevOpsWrapper.yml
  Jobs/PrGate.yml
Labels: type:bug

#250 .sync/Version.njk: Update Mu repos to Mu DevOps v6.4.1
  .sync/Version.njk
Labels: semver:patch

#251 .sync/Files.yml: Drop Makefile.toml sync to mu_rust_hid
  .sync/Files.yml
Labels: semver:patch

#252 Steps/RustCargoSteps.yml: Parameterize commands
  .sync/azure_pipelines/MuDevOpsWrapper.yml
  Steps/RustCargoSteps.yml
Labels: type:design-change

#255 .sync/Version.njk: Update Mu repos to Mu DevOps v6.5.1
  .sync/Version.njk
Labels: semver:patch
