Repository microsoft/mu_devops, pull requests merged in 2023-04, with the labels that each got.

#156 codeql.yml: Remove PIP caching from pkg gathering
  .sync/workflows/leaf/codeql.yml
Labels: type:bug

#167 Add quotes to git safe.directory in .devcontainer to fix parsing error
  .sync/devcontainer/devcontainer.json
Labels: type:bug

#168 .sync/codeql: Attempt to upload logs in case of success and failures
  .sync/workflows/leaf/codeql.yml
Labels: type:enhancement

#169 Add Issue Assignment workflow
  .github/workflows/IssueAssignment.yml
  .sync/Files.yml
  .sync/workflows/leaf/issue-assignment.yml
  ReadMe.rst
Labels: type:enhancement

#171 <Binary/Other>CopyAndPublish.yml: Use bash to parse parameter string
  Steps/BinaryCopyAndPublish.yml
  Steps/OtherCopyAndPublish.yml
Labels: semver:patch
