Repository microsoft/mu_devops, pull requests merged in 2023-11, with the labels that each got.

#268 .sync/Version.njk: Update Mu repos to Mu DevOps v7.1.0
  .sync/Version.njk
Labels: semver:patch

#270 MuDevOpsWrapper: Allow coverage uploads to ado or codecov.io
  .sync/Version.njk
  .sync/azure_pipelines/MuDevOpsWrapper.yml
  Jobs/PrGate.yml
  Steps/PrGate.yml
  Steps/PublishCodeCoverage.yml
  Steps/UploadCodeCoverage.yml
Labels: type:feature-request

#274 Steps/UploadCodeCoverage.yml: Remove dependency and conditionalize [Rebase & FF]
  Steps/UploadCodeCoverage.yml
Labels: type:design-change

#273 Jobs/PrGate.yml: Update Code Coverage commands
  .sync/Version.njk
  Jobs/PrGate.yml
Labels: impact:breaking-change, type:design-change

#277 Multiple Updates to code coverage
  .sync/Version.njk
  .sync/azure_pipelines/MuDevOpsWrapper.yml
  Jobs/PrGate.yml
  ReadMe.rst
  Steps/PrGate.yml
  Steps/UploadCodeCoverage.yml
Labels: impact:breaking-change

#279 MuDevOpsWrapper.yml: Bugfix bad value options
  .sync/azure_pipelines/MuDevOpsWrapper.yml
  Jobs/PrGate.yml
  ReadMe.rst
  Steps/PrGate.yml
  Steps/UploadCodeCoverage.yml
Labels: impact:non-functional
