Repository microsoft/mu_devops, pull requests merged in 2023-02, with the labels that each got.

#99 Update Fedora 35 Build container image to 5b8a008
  .sync/Version.njk
  Jobs/PrGate.yml
Labels: semver:minor

#101 Elaborate on check list items in PR template
  .sync/github_templates/pull_requests/pull_request_template.md
Labels: type:documentation, impact:non-functional

#103 Add security policy for file syncing
  .sync/Files.yml
  .sync/github_templates/contributing/CONTRIBUTING.md
  .sync/github_templates/security/SECURITY.md
Labels: type:documentation, complexity:easy

#104 .sync/Version.njk: Update Mu repos to Mu DevOps v1.7.4
  .sync/Version.njk
Labels: semver:patch

#97 .sync/Files.yml: Sync release drafter to feature and platform repos
  .sync/Files.yml
Labels: type:enhancement

#40 Add NuGet publishing
  Jobs/CreateBuildMatrix.yml
  Jobs/PrGate.yml
  Steps/BinaryCopyAndPublish.yml
  Steps/BuildBaseTools.yml
  Steps/BuildPlatform.yml
  Steps/CommonLogCopyAndPublish.yml
  Steps/NuGet.yml
  Steps/OtherCopyAndPublish.yml
  Steps/PrGate.yml
  Steps/SetupPythonPreReqs.yml
Labels: type:enhancement, impact:breaking-change, semver:major

#106 .sync/SECURITY.md: Fix markdownlint errors
  .sync/github_templates/security/SECURITY.md
Labels: type:bug

#112 Re-introduce workaround to fix ADO path names for PR eval
  Steps/BuildPlatform.yml
  Steps/PrGate.yml
Labels: type:bug

#113 .sync/Version.njk: Update Mu repos to Mu DevOps v2.0.1
  .github/workflows/release-draft.yml
  .sync/Version.njk
Labels: urgency:medium

#118 .sync/workflows/leaf: Add PR formatting validator workflow
  .sync/Files.yml
  .sync/workflows/leaf/pull-request-formatting-validator.yml
  ReadMe.rst
Labels: type:enhancement

#120 release-draft-config.yml: Add breaking changes section
  .sync/workflows/config/release-draft/release-draft-config.yml
Labels: type:feature-request
