Repository microsoft/mu_devops, pull requests merged in 2024-01, with the labels that each got.

#299 .sync/workflows/leaf/codeql.yml: Update CodeQL plugin from .pytool to BaseTools
  .sync/workflows/leaf/codeql-platform.yml
  .sync/workflows/leaf/codeql.yml
Labels: type:design-change

#301 .sync/workflows/codeql: Update sync action to v4
  .sync/workflows/leaf/codeql-platform.yml
  .sync/workflows/leaf/codeql.yml
Labels: semver:patch

#303 Fix issue with .pytool/Plugin removal which was introduced with the latest codeql.yml change.
  .sync/workflows/leaf/codeql.yml
Labels: type:bug

#307 GitHub Action: Bump robinraju/release-downloader from 1.8 to 1.9
  .sync/workflows/leaf/codeql-platform.yml
  .sync/workflows/leaf/codeql.yml
Labels: semver:patch

#305 workflows: Add permissions.
  .github/workflows/AutoMerger.yml
  .github/workflows/FileSyncer.yml
  .github/workflows/IssueAssignment.yml
  .github/workflows/IssueTriager.yml
  .github/workflows/LabelSyncer.yml
  .github/workflows/Labeler.yml
  .github/workflows/ReleaseDrafter.yml
  .sync/Version.njk
  .sync/workflows/leaf/auto-approve.yml
  .sync/workflows/leaf/auto-merge.yml
  .sync/workflows/leaf/issue-assignment.yml
  .sync/workflows/leaf/label-issues.yml
  .sync/workflows/leaf/label-sync.yml
  .sync/workflows/leaf/pull-request-formatting-validator.yml
  .sync/workflows/leaf/release-draft.yml
  .sync/workflows/leaf/scheduled-maintenance.yml
  .sync/workflows/leaf/stale.yml
  .sync/workflows/leaf/submodule-release-update.yml
  .sync/workflows/leaf/triage-issues.yml
Labels: impact:security, complexity:easy
