Repository microsoft/mu_devops, pull requests merged in 2024-07, with the labels that each got.

#351 .sync/workflows/codeql: Bump release-downloader from v1.10 to v1.11
  .sync/workflows/leaf/codeql-platform.yml
  .sync/workflows/leaf/codeql.yml
Labels: semver:patch

#353 .sync/rust_config/Makefile.toml: Add clippy to catch lint issues duri…
  .sync/rust_config/Makefile.toml
Labels: type:enhancement

#354 Jobs/PrGate.yml: Fix 'CLANGPDB' string expression issue
  Jobs/PrGate.yml
Labels: type:bug

#355 Steps/BuildPlatform.yml & Steps/PrGate.yml: Introduce publish_artifacts parameter
  Steps/BinaryCopyAndPublish.yml
  Steps/BuildPlatform.yml
  Steps/CommonLogCopyAndPublish.yml
  Steps/OtherCopyAndPublish.yml
  Steps/PrGate.yml
Labels: type:design-change
