Repository microsoft/mu_devops, pull requests merged in 2024-09, with the labels that each got.

#363 RustSetupSteps.yml: Update to latest cargo_tarpaulin 31.2 and Rust Toolchain
  .sync/Version.njk
Labels: impact:breaking-change

#369 .sync/dependabot: Add Features/DEBUGGER to ignore list
  .sync/dependabot/actions-pip-submodules.yml
Labels: semver:patch

#373 Build-Containers.yml: Trigger on Version.njk change
  .github/workflows/Build-Containers.yml
Labels: semver:patch

#374 Version.njk: Update to container version d1e4ff1
  .sync/Version.njk
Labels: semver:patch

#378 PrGate.yml: Add extra_pre_build_steps param
  Jobs/PrGate.yml
  Steps/PrGate.yml
Labels: type:feature-request

#377 Containers: Update QEMU to version 9.0.0
  Containers/Ubuntu-22/Dockerfile
Labels: semver:minor
