Repository microsoft/mu_devops, pull requests merged in 2024-05, with the labels that each got.

#333 Prevent line ending conversion in repos
  .sync/Files.yml
  .sync/git_templates/gitattributes_template.txt
Labels: type:feature-request

#342 Steps/BuildPlatform.yml & Steps/PrGate.yml: Add parameter to install pip modules
  Steps/BuildPlatform.yml
  Steps/PrGate.yml
Labels: semver:patch

#343 remove `-a` flag on stuart_build commands
  .sync/Version.njk
  Steps/BuildPlatform.yml
  Steps/PrGate.yml
Labels: impact:breaking-change
